### PR TITLE
fix: issue #10 - Interactivity

### LINKED ISSUE #10: Interactivity
- How do you make a component interactive? - events
- Creation and adding event handlers
- Dos and Don'ts
- Passing event handlers as props
- Naming event handler props
- Propagation 

 Use the interaction.md file or create one if it doesn't exist yet.

### PR DESCRIPTION
**Pull request by Stan015**
a detailed note on interactivity in react

### CODE REVIEW

**Review by Oluwasetemi — APPROVED** [review]

**Comment by Oluwasetemi** [comment]
@Stan015 for the interactivity PR can add something on state, because that is also a form of interaction. Its critical to the subject of interactivity.

**Comment by Stan015** [comment]
> @Stan015 for the interactivity PR can add something on state, because that is also a form of interaction. Its critical to the subject of interactivity.

True. I will carefully make a PR in this regard.

**Comment by victorvictoria-maker** [comment]
Welldone @Stan015

Please, check the Creating and Adding Event Handlers sub-section, the style for 'event handlers' is not being applied and is displaying as plain text.

**Review by Oluwasetemi — APPROVED** [review]

**Comment by Stan015** [comment]
> @Stan015 for the interactivity PR can add something on state, because that is also a form of interaction. Its critical to the subject of interactivity.

added a slide for state as to regards to interactivity.

**Comment by Stan015** [comment]
> Welldone @Stan015
> 
> Please, check the Creating and Adding Event Handlers sub-section, the style for 'event handlers' is not being applied and is displaying as plain text.

I have fixed this. Kindly check.

**Pull request merged**
