### PR TITLE
fix: issue 15 - more hooks

### LINKED ISSUE #15: More Hooks
- useReducer
- useContext
- useRef
- useLayoutEffect

 Use the more-hooks.md file or create one if it doesn't exist yet.

### PR DESCRIPTION
**Pull request by victorvictoria-maker**

### CODE REVIEW

**Review by Stan015 — COMMENTED** [review]
Well done, Victoria 👏

My overall review is that it's a great note. Although the note is missing one last topic; "useLayoutEffect". 

useLayoutEffect may have a pitfall and useEffect is preferred but you can still hint on it. 

Just a suggestion, if it's not that important we can go ahead to merge ☑️

**Comment by victorvictoria-maker** [comment]
Thank you @Stan015. I avoided useLayoutEffect as it blocks rendering and impacts performance, preferring useEffect or  the new use hook for modern stuffs.

**Comment by Oluwasetemi** [comment]
I just think its worth noting so that student are aware of its possible usage. Maybe linking it to the React.dev page. Did we include  hook?

**Comment by Oluwasetemi** [comment]
I just think its worth noting so that student are aware of its possible usage. Maybe linking it to the React.dev page. Did we include `useDeferred` hook?

**Comment by victorvictoria-maker** [comment]
Noted @Oluwasetemi .
I would include it.

useDeferred hook was not included. I would add it to the note also.

**Review by Oluwasetemi — APPROVED** [review]

**Pull request merged**
